name: Construccion de imagen y despliegue con docker en EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Construir imagen de Docker y subir al repositorio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .                    # Directorio donde está el Dockerfile
          push: true                    # Subir la imagen a Docker Hub
          tags: dalyanacarvajal/isa-docker:flaskapp

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}   # Cambiado de 'hosts' a 'host'
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull dalyanacarvajal/isa-docker:flaskapp
            docker stop contflaskdaly || true
            docker rm contflaskdaly || true
            docker run -d --name contflaskdaly -p 8080:5000 dalyanacarvajal/isa-docker:flaskapp
